version: '3.8'

services:

  airflow-postgres:
    image: postgres:14
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-postgres-data:/var/lib/postgresql/data
    networks:
      - kyda-network

  airflow-redis:
    image: redis:7
    container_name: airflow-redis
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - kyda-network

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: airflow-webserver
    command: webserver
    restart: always
    env_file:
      - ./env-airflow.env
    volumes:
      - ../../dags:/opt/airflow/dags
      - ./airflow.cfg:/opt/airflow/airflow.cfg
    depends_on:
      - airflow-postgres
      - airflow-redis
      - airflow-scheduler
      - airflow-worker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airflow.rule=Host(`airflow.kyda.tech`)"
      - "traefik.http.routers.airflow.entrypoints=websecure"
      - "traefik.http.services.airflow.loadbalancer.server.port=8080"
    networks:
      - kyda-network

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow-scheduler
    command: scheduler
    restart: always
    env_file:
      - ./env-airflow.env
    volumes:
      - ../../dags:/opt/airflow/dags
      - ./airflow.cfg:/opt/airflow/airflow.cfg
    networks:
      - kyda-network
    depends_on:
      - airflow-postgres
      - airflow-redis

  airflow-worker:
    image: apache/airflow:2.8.1
    container_name: airflow-worker
    command: celery worker
    restart: always
    env_file:
      - ./env-airflow.env
    volumes:
      - ../../dags:/opt/airflow/dags
      - ./airflow.cfg:/opt/airflow/airflow.cfg
    networks:
      - kyda-network
    depends_on:
      - airflow-scheduler

  airflow-flower:
    image: apache/airflow:2.8.1
    container_name: airflow-flower
    command: celery flower
    restart: always
    env_file:
      - ./env-airflow.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flower.rule=Host(`flower.kyda.tech`)"
      - "traefik.http.routers.flower.entrypoints=websecure"
      - "traefik.http.services.flower.loadbalancer.server.port=5555"
    networks:
      - kyda-network
    depends_on:
      - airflow-redis

volumes:
  airflow-postgres-data:

networks:
  kyda-network:
    external: true

